---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: yes

- name: Ensure the required packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - openjdk-11-jre-headless
